# Generated by Django 3.1.4 on 2020-12-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ticket_prize',
            new_name='ticket_price',
        ),
    ]
